export default {
  nav: { downloader: 'تنزيل', queue: 'القائمة', batch: 'دفعة', settings: 'الإعدادات', console: 'السجل' },
  banner: { checking: 'جارٍ التحقق من ملف yt-dlp…', ffmpegReady: 'ffmpeg جاهز', ffmpegMissing: 'لم يتم العثور على ffmpeg — الدمج والتحويل معطّلان', updateAvailable: 'تحديث متاح', update: 'تحديث', download: 'تنزيل', installed: 'مثبَّت' },
  welcome: { title: 'مرحباً بك في ytdl-gui', subtitle: 'واجهة متميزة لـ yt-dlp — قم بالتنزيل من أكثر من 1000 موقع', step1: { title: 'الميزات', desc: 'كل ما تحتاجه لتنزيل الفيديوهات والصوت وقوائم التشغيل' }, step2: { title: 'إعداد التبعيات', desc: 'نحتاج إلى تنزيل yt-dlp للبدء' }, step3: { title: 'اختيار اللغة', desc: 'اختر لغتك المفضلة' }, features: { formats: { title: 'أي تنسيق', desc: 'MP4, MP3, WebM, AV1, 4K, 8K, HDR' }, queue: { title: 'قائمة التنزيل', desc: 'تقدم في الوقت الفعلي والسرعة والوقت المتبقي' }, batch: { title: 'دفعة وقناة', desc: 'تنزيل قنوات كاملة أو قوائم روابط' }, console: { title: 'وحدة التحكم المباشرة', desc: 'إخراج الطرفية الخام للمستخدمين المتقدمين' } }, checking: 'جارٍ التحقق…', ytdlpFound: 'yt-dlp {{version}} — جاهز!', ytdlpMissing: 'لم يتم العثور على yt-dlp', ffmpegFound: 'ffmpeg — جاهز!', ffmpegMissing: 'لم يتم العثور على ffmpeg', downloadYtdlp: 'تنزيل yt-dlp', downloading: 'جارٍ التنزيل… {{pct}}%', done: 'كل شيء جاهز!', getStarted: 'ابدأ', next: 'التالي', back: 'رجوع', skip: 'تخطي' },
  downloader: { title: 'تنزيل جديد', subtitle: 'قم بالتكوين وابدأ التنزيل', reset: 'إعادة تعيين', start: 'بدء التنزيل', preview: 'معاينة الأمر', basic: 'أساسي', quality: 'الجودة والترميز', post: 'ما بعد المعالجة', playlist: 'قائمة التشغيل', network: 'الشبكة والمصادقة', advanced: 'متقدم', url: 'رابط', urlHint: 'يوتيوب وفيميو وتويتر وساوند كلاود وأكثر من 1000 موقع', outputDir: 'مجلد الوجهة', format: 'التنسيق', audioQuality: 'جودة الصوت', customFormat: 'تنسيق مخصص', resolution: 'أقصى دقة', codec: 'تفضيل برنامج الترميز', hdr: 'تفضيل HDR', hdrHint: 'تنزيل إصدار HDR إذا كان متاحاً', embedSubs: 'تضمين الترجمات', embedSubsHint: 'تنزيل الترجمات وتضمينها', subLangs: 'لغات الترجمة', subLangsHint: 'مثال: "ar,en" أو "all"', embedMetadata: 'تضمين البيانات الوصفية', embedChapters: 'تضمين الفصول', embedThumbnail: 'تضمين الصورة المصغرة', sponsorblock: 'SponsorBlock', sponsorblockHint: 'إزالة المقاطع الممولة تلقائياً', audioConvert: 'تحويل الصوت', audioConvertHint: 'إعادة ترميز الصوت للتنسيق المختار', audioFormat: 'تنسيق الإخراج', proxy: 'رابط البروكسي', proxyHint: 'http://بروكسي:منفذ أو socks5://…', rateLimit: 'حد السرعة', rateLimitHint: 'مثال: 1M، 500K', concurrent: 'الأجزاء المتزامنة', concurrentHint: 'تنزيل الأجزاء بالتوازي', cookiesFile: 'ملف الكوكيز', noPlaylist: 'مقطع واحد فقط', noPlaylistHint: 'تجاهل قائمة التشغيل', playlistStart: 'مؤشر البداية', playlistEnd: 'مؤشر النهاية', extraArgs: 'حجج إضافية', extraArgsHint: 'تُضاف حرفياً لأمر yt-dlp', cmdPreview: 'معاينة الأمر' },
  queue: { title: 'قائمة التنزيل', active: '{{n}} نشط', noActive: 'لا توجد تنزيلات نشطة', completed: '{{n}} مكتمل', empty: 'لا توجد تنزيلات', emptyHint: 'انتقل إلى تبويب التنزيل للبدء', startOne: 'بدء تنزيل', clearDone: 'مسح المكتملة', cancel: 'إلغاء', openFolder: 'فتح المجلد', status: { queued: 'في الانتظار', downloading: 'جارٍ التنزيل', processing: 'جارٍ المعالجة', done: 'مكتمل', error: 'خطأ', cancelled: 'ملغى' } },
  batch: { title: 'التنزيل الدفعي', subtitle: 'تنزيل روابط متعددة أو قناة كاملة', tabUrls: 'قائمة الروابط', tabChannel: 'قناة / قائمة تشغيل', urlsLabel: 'الروابط (رابط واحد في كل سطر)', urlsPlaceholder: 'https://youtube.com/watch?v=...', urlsHint: 'الصق رابطاً واحداً في كل سطر', channelUrl: 'رابط القناة / قائمة التشغيل', channelPlaceholder: 'https://www.youtube.com/@القناة', limitVideos: 'تحديد عدد الفيديوهات', limitHint: 'الحد الأقصى للفيديوهات (0 = الكل)', dateAfter: 'فقط بعد التاريخ', dateBefore: 'فقط قبل التاريخ', reverseOrder: 'ترتيب عكسي', reverseOrderHint: 'البدء من أقدم فيديو في القناة', skipExisting: 'تخطي المنزَّلة مسبقاً', skipExistingHint: 'استخدام --download-archive', archiveFile: 'مسار ملف الأرشيف', archiveHint: 'ملف يتتبع التنزيلات المكتملة', startBatch: 'إضافة {{n}} إلى القائمة', startChannel: 'تنزيل القناة', urlCount: '{{n}} رابط', noUrls: 'لم تُدخل أي روابط بعد' },
  settings: { title: 'الإعدادات', subtitle: 'إدارة التطبيق والملفات الثنائية', binary: 'الملف الثنائي yt-dlp', status: 'الحالة', installed: 'مثبَّت', missing: 'مفقود', localVersion: 'الإصدار المحلي', latestVersion: 'أحدث إصدار', redownload: 'إعادة التنزيل', updateTo: 'التحديث إلى {{v}}', downloadLatest: 'تنزيل {{v}}', language: 'اللغة', languageHint: 'اختر لغة العرض المفضلة', about: 'حول', appName: 'التطبيق', version: 'الإصدار', framework: 'الإطار', poweredBy: 'مدعوم بـ', platform: 'المنصة' },
};
