export default {
  nav: { downloader: 'Descargas', queue: 'Cola', batch: 'Lotes', settings: 'Config.', console: 'Log' },
  banner: { checking: 'Verificando binario yt-dlp…', ffmpegReady: 'ffmpeg listo', ffmpegMissing: 'ffmpeg no encontrado — mezcla y conversión desactivadas', updateAvailable: 'Actualización disponible', update: 'Actualizar', download: 'Descargar', installed: 'Instalado' },
  welcome: {
    title: 'Bienvenido a ytdl-gui', subtitle: 'Una interfaz premium para yt-dlp — descarga de más de 1000 sitios',
    step1: { title: 'Características', desc: 'Todo lo que necesitas para descargar vídeos, audio y listas' },
    step2: { title: 'Configurar Dependencias', desc: 'Necesitamos descargar yt-dlp para comenzar' },
    step3: { title: 'Elegir Idioma', desc: 'Selecciona tu idioma preferido' },
    features: { formats: { title: 'Cualquier Formato', desc: 'MP4, MP3, WebM, AV1, 4K, 8K, HDR' }, queue: { title: 'Cola de Descargas', desc: 'Progreso en tiempo real, velocidad y ETA' }, batch: { title: 'Lote y Canal', desc: 'Descarga canales completos o listas de enlaces' }, console: { title: 'Consola en Vivo', desc: 'Salida raw del terminal para usuarios avanzados' } },
    checking: 'Verificando…', ytdlpFound: 'yt-dlp {{version}} — listo!', ytdlpMissing: 'yt-dlp no encontrado', ffmpegFound: 'ffmpeg — listo!', ffmpegMissing: 'ffmpeg no encontrado', downloadYtdlp: 'Descargar yt-dlp', downloading: 'Descargando… {{pct}}%', done: '¡Todo listo!', getStarted: 'Comenzar', next: 'Siguiente', back: 'Atrás', skip: 'Omitir',
  },
  downloader: { title: 'Nueva Descarga', subtitle: 'Configura e inicia tu descarga', reset: 'Restablecer', start: 'Iniciar Descarga', preview: 'Vista previa', basic: 'Básico', quality: 'Calidad y Codecs', post: 'Postprocesado', playlist: 'Lista', network: 'Red y Autenticación', advanced: 'Avanzado', url: 'URL', urlHint: 'YouTube, Vimeo, Twitter, SoundCloud y más de 1000 sitios', outputDir: 'Carpeta de destino', format: 'Formato', audioQuality: 'Calidad de audio', customFormat: 'Formato personalizado', resolution: 'Resolución máxima', codec: 'Preferencia de codec', hdr: 'Preferir HDR', hdrHint: 'Descargar versión HDR si está disponible', embedSubs: 'Incrustar subtítulos', embedSubsHint: 'Descargar e incrustar subtítulos', subLangs: 'Idiomas de subtítulos', subLangsHint: 'p.ej. "es,en" o "all"', embedMetadata: 'Incrustar metadatos', embedChapters: 'Incrustar capítulos', embedThumbnail: 'Incrustar miniatura', sponsorblock: 'SponsorBlock', sponsorblockHint: 'Eliminar segmentos patrocinados', audioConvert: 'Convertir audio', audioConvertHint: 'Re-codificar audio al formato elegido', audioFormat: 'Formato de salida', proxy: 'URL del proxy', proxyHint: 'http://proxy:puerto o socks5://…', rateLimit: 'Límite de velocidad', rateLimitHint: 'p.ej. 1M, 500K', concurrent: 'Fragmentos simultáneos', concurrentHint: 'Descargas de fragmentos en paralelo', cookiesFile: 'Archivo de cookies', noPlaylist: 'Solo vídeo único', noPlaylistHint: 'Ignorar lista, descargar solo el vídeo del enlace', playlistStart: 'Índice inicial', playlistEnd: 'Índice final', extraArgs: 'Argumentos extra', extraArgsHint: 'Añadidos literalmente al comando yt-dlp', cmdPreview: 'Vista previa del comando' },
  queue: { title: 'Cola de Descargas', active: '{{n}} activo(s)', noActive: 'Sin descargas activas', completed: '{{n}} completado(s)', empty: 'Sin descargas aún', emptyHint: 'Ve a la pestaña Descargas para iniciar', startOne: 'Iniciar descarga', clearDone: 'Limpiar completados', cancel: 'Cancelar', openFolder: 'Abrir carpeta', status: { queued: 'En cola', downloading: 'Descargando', processing: 'Procesando', done: 'Completado', error: 'Error', cancelled: 'Cancelado' } },
  batch: { title: 'Descarga en Lote', subtitle: 'Descarga múltiples URLs o un canal completo', tabUrls: 'Lista de URLs', tabChannel: 'Canal / Lista', urlsLabel: 'URLs (una por línea)', urlsPlaceholder: 'https://youtube.com/watch?v=...\nhttps://vimeo.com/...', urlsHint: 'Pega una URL por línea', channelUrl: 'URL del canal / lista', channelPlaceholder: 'https://www.youtube.com/@canal', limitVideos: 'Limitar número de vídeos', limitHint: 'Máximo de vídeos (0 = todos)', dateAfter: 'Solo después de fecha', dateBefore: 'Solo antes de fecha', reverseOrder: 'Orden inverso', reverseOrderHint: 'Empezar por el más antiguo', skipExisting: 'Omitir ya descargados', skipExistingHint: 'Usar --download-archive', archiveFile: 'Ruta del archivo de control', archiveHint: 'Archivo que registra descargas completadas', startBatch: 'Agregar {{n}} a la cola', startChannel: 'Descargar canal', urlCount: '{{n}} URL{{s}}', noUrls: 'No hay URLs aún' },
  settings: { title: 'Ajustes', subtitle: 'Gestión de la aplicación y binarios', binary: 'Binario yt-dlp', status: 'Estado', installed: 'Instalado', missing: 'No encontrado', localVersion: 'Versión local', latestVersion: 'Última versión', redownload: 'Re-descargar', updateTo: 'Actualizar a {{v}}', downloadLatest: 'Descargar {{v}}', language: 'Idioma', languageHint: 'Elige tu idioma de visualización', about: 'Acerca de', appName: 'Aplicación', version: 'Versión', framework: 'Framework', poweredBy: 'Tecnología', platform: 'Plataforma' },
};
