export default {
  nav: { downloader: 'Download', queue: 'Coda', batch: 'Batch', settings: 'Impost.', console: 'Log' },
  banner: { checking: 'Verifica binario yt-dlp…', ffmpegReady: 'ffmpeg pronto', ffmpegMissing: 'ffmpeg non trovato — unione e conversione disabilitate', updateAvailable: 'Aggiornamento disponibile', update: 'Aggiorna', download: 'Scarica', installed: 'Installato' },
  welcome: { title: 'Benvenuto in ytdl-gui', subtitle: 'Un\'interfaccia premium per yt-dlp — scarica da oltre 1000 siti', step1: { title: 'Funzionalità', desc: 'Tutto ciò che ti serve per scaricare video, audio e playlist' }, step2: { title: 'Configura Dipendenze', desc: 'Dobbiamo scaricare yt-dlp per iniziare' }, step3: { title: 'Scegli Lingua', desc: 'Seleziona la tua lingua preferita' }, features: { formats: { title: 'Qualsiasi Formato', desc: 'MP4, MP3, WebM, AV1, 4K, 8K, HDR' }, queue: { title: 'Coda Download', desc: 'Progresso in tempo reale, velocità e ETA' }, batch: { title: 'Batch e Canale', desc: 'Scarica canali interi o liste di link' }, console: { title: 'Console Live', desc: 'Output raw del terminale per utenti avanzati' } }, checking: 'Verifica…', ytdlpFound: 'yt-dlp {{version}} — pronto!', ytdlpMissing: 'yt-dlp non trovato', ffmpegFound: 'ffmpeg — pronto!', ffmpegMissing: 'ffmpeg non trovato', downloadYtdlp: 'Scarica yt-dlp', downloading: 'Scaricamento… {{pct}}%', done: 'Tutto pronto!', getStarted: 'Inizia', next: 'Avanti', back: 'Indietro', skip: 'Salta' },
  downloader: { title: 'Nuovo Download', subtitle: 'Configura e avvia il download', reset: 'Reimposta', start: 'Avvia Download', preview: 'Anteprima comando', basic: 'Base', quality: 'Qualità e Codec', post: 'Post-elaborazione', playlist: 'Playlist', network: 'Rete e Auth.', advanced: 'Avanzato', url: 'URL', urlHint: 'YouTube, Vimeo, Twitter, SoundCloud e oltre 1000 siti', outputDir: 'Cartella di destinazione', format: 'Formato', audioQuality: 'Qualità audio', customFormat: 'Formato personalizzato', resolution: 'Risoluzione massima', codec: 'Preferenza codec', hdr: 'Preferisci HDR', hdrHint: 'Scarica versione HDR se disponibile', embedSubs: 'Incorpora sottotitoli', embedSubsHint: 'Scarica e incorpora i sottotitoli', subLangs: 'Lingue sottotitoli', subLangsHint: 'es. "it,en" o "all"', embedMetadata: 'Incorpora metadati', embedChapters: 'Incorpora capitoli', embedThumbnail: 'Incorpora miniatura', sponsorblock: 'SponsorBlock', sponsorblockHint: 'Rimuovi segmenti sponsorizzati', audioConvert: 'Converti audio', audioConvertHint: 'Ri-codifica audio nel formato scelto', audioFormat: 'Formato output', proxy: 'URL proxy', proxyHint: 'http://proxy:porta o socks5://…', rateLimit: 'Limite velocità', rateLimitHint: 'es. 1M, 500K', concurrent: 'Frammenti simultanei', concurrentHint: 'Download frammenti in parallelo', cookiesFile: 'File cookie', noPlaylist: 'Solo video singolo', noPlaylistHint: 'Ignora playlist', playlistStart: 'Indice iniziale', playlistEnd: 'Indice finale', extraArgs: 'Argomenti extra', extraArgsHint: 'Aggiunti letteralmente al comando yt-dlp', cmdPreview: 'Anteprima comando' },
  queue: { title: 'Coda Download', active: '{{n}} attivo/i', noActive: 'Nessun download attivo', completed: '{{n}} completato/i', empty: 'Nessun download', emptyHint: 'Vai alla scheda Download per iniziare', startOne: 'Avvia download', clearDone: 'Elimina completati', cancel: 'Annulla', openFolder: 'Apri cartella', status: { queued: 'In coda', downloading: 'Scaricamento', processing: 'Elaborazione', done: 'Completato', error: 'Errore', cancelled: 'Annullato' } },
  batch: { title: 'Download Batch', subtitle: 'Scarica più URL o un intero canale', tabUrls: 'Lista URL', tabChannel: 'Canale / Playlist', urlsLabel: 'URL (una per riga)', urlsPlaceholder: 'https://youtube.com/watch?v=...', urlsHint: 'Incolla un URL per riga', channelUrl: 'URL canale / playlist', channelPlaceholder: 'https://www.youtube.com/@canale', limitVideos: 'Limita numero video', limitHint: 'Massimo video (0 = tutti)', dateAfter: 'Solo dopo la data', dateBefore: 'Solo prima della data', reverseOrder: 'Ordine inverso', reverseOrderHint: 'Inizia dal più vecchio', skipExisting: 'Salta già scaricati', skipExistingHint: 'Usa --download-archive', archiveFile: 'Percorso file archivio', archiveHint: 'File che traccia i download completati', startBatch: 'Aggiungi {{n}} alla coda', startChannel: 'Scarica canale', urlCount: '{{n}} URL{{s}}', noUrls: 'Nessun URL inserito' },
  settings: { title: 'Impostazioni', subtitle: 'Gestione applicazione e binari', binary: 'Binario yt-dlp', status: 'Stato', installed: 'Installato', missing: 'Mancante', localVersion: 'Versione locale', latestVersion: 'Ultima versione', redownload: 'Ri-scarica', updateTo: 'Aggiorna a {{v}}', downloadLatest: 'Scarica {{v}}', language: 'Lingua', languageHint: 'Scegli la lingua di visualizzazione', about: 'Informazioni', appName: 'Applicazione', version: 'Versione', framework: 'Framework', poweredBy: 'Tecnologia', platform: 'Piattaforma' },
};
