export default {
  nav: { downloader: 'DL', queue: 'キュー', batch: 'バッチ', settings: '設定', console: 'ログ' },
  banner: { checking: 'yt-dlpバイナリを確認中…', ffmpegReady: 'ffmpeg 準備完了', ffmpegMissing: 'ffmpegが見つかりません — マージと変換が無効', updateAvailable: 'アップデート利用可能', update: '更新', download: 'ダウンロード', installed: 'インストール済み' },
  welcome: { title: 'ytdl-guiへようこそ', subtitle: 'yt-dlpのプレミアムインターフェース — 1000以上のサイトからダウンロード', step1: { title: '機能', desc: 'ビデオ、オーディオ、プレイリストのダウンロードに必要なすべて' }, step2: { title: '依存関係の設定', desc: '開始するにはyt-dlpをダウンロードする必要があります' }, step3: { title: '言語を選択', desc: '希望する言語を選択してください' }, features: { formats: { title: 'あらゆる形式', desc: 'MP4, MP3, WebM, AV1, 4K, 8K, HDR' }, queue: { title: 'ダウンロードキュー', desc: 'リアルタイム進捗、速度、ETA' }, batch: { title: 'バッチとチャンネル', desc: 'チャンネル全体やリンクリストをダウンロード' }, console: { title: 'ライブコンソール', desc: '上級者向けの生のターミナル出力' } }, checking: '確認中…', ytdlpFound: 'yt-dlp {{version}} — 準備完了!', ytdlpMissing: 'yt-dlpが見つかりません', ffmpegFound: 'ffmpeg — 準備完了!', ffmpegMissing: 'ffmpegが見つかりません', downloadYtdlp: 'yt-dlpをダウンロード', downloading: 'ダウンロード中… {{pct}}%', done: '準備完了！', getStarted: '始める', next: '次へ', back: '戻る', skip: 'スキップ' },
  downloader: { title: '新規ダウンロード', subtitle: 'ダウンロードを設定して開始', reset: 'リセット', start: 'ダウンロード開始', preview: 'コマンドプレビュー', basic: '基本', quality: '品質とコーデック', post: '後処理', playlist: 'プレイリスト', network: 'ネットワークと認証', advanced: '詳細', url: 'URL', urlHint: 'YouTube、Vimeo、Twitter、SoundCloudなど1000以上のサイト', outputDir: '出力ディレクトリ', format: 'フォーマット', audioQuality: '音質', customFormat: 'カスタムフォーマット', resolution: '最大解像度', codec: 'ビデオコーデックの優先順位', hdr: 'HDRを優先', hdrHint: '利用可能な場合はHDRバージョンをダウンロード', embedSubs: '字幕を埋め込む', embedSubsHint: '字幕をダウンロードして埋め込む', subLangs: '字幕言語', subLangsHint: '例: "ja,en" または "all"', embedMetadata: 'メタデータを埋め込む', embedChapters: 'チャプターを埋め込む', embedThumbnail: 'サムネイルを埋め込む', sponsorblock: 'SponsorBlock', sponsorblockHint: 'スポンサーセグメントを自動削除', audioConvert: 'オーディオ変換', audioConvertHint: 'オーディオを選択した形式に再エンコード', audioFormat: '出力フォーマット', proxy: 'プロキシURL', proxyHint: 'http://プロキシ:ポート または socks5://…', rateLimit: '速度制限', rateLimitHint: '例: 1M、500K', concurrent: '同時フラグメント', concurrentHint: '並列フラグメントダウンロード', cookiesFile: 'Cookieファイル', noPlaylist: '単一動画のみ', noPlaylistHint: 'プレイリストを無視', playlistStart: '開始インデックス', playlistEnd: '終了インデックス', extraArgs: '追加引数', extraArgsHint: 'yt-dlpコマンドに逐語的に追加', cmdPreview: 'コマンドプレビュー' },
  queue: { title: 'ダウンロードキュー', active: '{{n}}件アクティブ', noActive: 'アクティブなダウンロードなし', completed: '{{n}}件完了', empty: 'ダウンロードなし', emptyHint: 'ダウンロードタブに移動して開始', startOne: 'ダウンロード開始', clearDone: '完了済みをクリア', cancel: 'キャンセル', openFolder: 'フォルダを開く', status: { queued: 'キュー待ち', downloading: 'ダウンロード中', processing: '処理中', done: '完了', error: 'エラー', cancelled: 'キャンセル済み' } },
  batch: { title: 'バッチダウンロード', subtitle: '複数のURLまたはチャンネル全体をダウンロード', tabUrls: 'URLリスト', tabChannel: 'チャンネル / プレイリスト', urlsLabel: 'URL（1行に1つ）', urlsPlaceholder: 'https://youtube.com/watch?v=...', urlsHint: '1行に1つのURLを貼り付け', channelUrl: 'チャンネル / プレイリストURL', channelPlaceholder: 'https://www.youtube.com/@チャンネル', limitVideos: '動画数を制限', limitHint: '最大動画数（0=すべて）', dateAfter: '指定日以降のみ', dateBefore: '指定日以前のみ', reverseOrder: '逆順（古い順）', reverseOrderHint: 'チャンネルの最も古い動画から開始', skipExisting: 'ダウンロード済みをスキップ', skipExistingHint: '--download-archiveを使用', archiveFile: 'アーカイブファイルパス', archiveHint: '完了したダウンロードを追跡するファイル', startBatch: '{{n}}件をキューに追加', startChannel: 'チャンネルをダウンロード', urlCount: '{{n}}件のURL', noUrls: 'URLがまだ入力されていません' },
  settings: { title: '設定', subtitle: 'アプリケーションとバイナリの管理', binary: 'yt-dlpバイナリ', status: 'ステータス', installed: 'インストール済み', missing: '見つかりません', localVersion: 'ローカルバージョン', latestVersion: '最新バージョン', redownload: '再ダウンロード', updateTo: '{{v}}に更新', downloadLatest: '{{v}}をダウンロード', language: '言語', languageHint: '表示言語を選択', about: 'について', appName: 'アプリケーション', version: 'バージョン', framework: 'フレームワーク', poweredBy: '使用技術', platform: 'プラットフォーム' },
};
