export default {
  nav: { downloader: '下载', queue: '队列', batch: '批量', settings: '设置', console: '日志' },
  banner: { checking: '正在检查 yt-dlp 二进制文件…', ffmpegReady: 'ffmpeg 就绪', ffmpegMissing: '未找到 ffmpeg — 合并和转换已禁用', updateAvailable: '有可用更新', update: '更新', download: '下载', installed: '已安装' },
  welcome: { title: '欢迎使用 ytdl-gui', subtitle: 'yt-dlp 的高级界面 — 从 1000+ 个网站下载', step1: { title: '功能', desc: '下载视频、音频和播放列表所需的一切' }, step2: { title: '配置依赖项', desc: '我们需要下载 yt-dlp 才能开始' }, step3: { title: '选择语言', desc: '选择您的首选语言' }, features: { formats: { title: '任何格式', desc: 'MP4, MP3, WebM, AV1, 4K, 8K, HDR' }, queue: { title: '下载队列', desc: '实时进度、速度和 ETA' }, batch: { title: '批量和频道', desc: '下载整个频道或链接列表' }, console: { title: '实时控制台', desc: '高级用户的原始终端输出' } }, checking: '检查中…', ytdlpFound: 'yt-dlp {{version}} — 就绪!', ytdlpMissing: '未找到 yt-dlp', ffmpegFound: 'ffmpeg — 就绪!', ffmpegMissing: '未找到 ffmpeg', downloadYtdlp: '下载 yt-dlp', downloading: '下载中… {{pct}}%', done: '一切就绪！', getStarted: '开始使用', next: '下一步', back: '返回', skip: '跳过' },
  downloader: { title: '新建下载', subtitle: '配置并开始下载', reset: '重置', start: '开始下载', preview: '预览命令', basic: '基本', quality: '质量和编解码器', post: '后处理', playlist: '播放列表', network: '网络和认证', advanced: '高级', url: 'URL', urlHint: 'YouTube、Vimeo、Twitter、SoundCloud 等 1000+ 个网站', outputDir: '输出目录', format: '格式', audioQuality: '音频质量', customFormat: '自定义格式字符串', resolution: '最大分辨率', codec: '视频编解码器偏好', hdr: '偏好 HDR', hdrHint: '如果可用则下载 HDR 版本', embedSubs: '嵌入字幕', embedSubsHint: '下载并嵌入字幕', subLangs: '字幕语言', subLangsHint: '例如 "zh,en" 或 "all"', embedMetadata: '嵌入元数据', embedChapters: '嵌入章节', embedThumbnail: '嵌入缩略图', sponsorblock: 'SponsorBlock', sponsorblockHint: '自动删除赞助片段', audioConvert: '转换音频', audioConvertHint: '将音频重新编码为所选格式', audioFormat: '输出格式', proxy: '代理 URL', proxyHint: 'http://代理:端口 或 socks5://…', rateLimit: '速率限制', rateLimitHint: '例如 1M、500K', concurrent: '并发片段', concurrentHint: '并行片段下载', cookiesFile: 'Cookie 文件', noPlaylist: '仅单个视频', noPlaylistHint: '忽略播放列表', playlistStart: '开始索引', playlistEnd: '结束索引', extraArgs: '额外参数', extraArgsHint: '逐字添加到 yt-dlp 命令', cmdPreview: '命令预览' },
  queue: { title: '下载队列', active: '{{n}} 个活动', noActive: '没有活动下载', completed: '{{n}} 个完成', empty: '暂无下载', emptyHint: '前往下载标签页开始下载', startOne: '开始下载', clearDone: '清除已完成', cancel: '取消', openFolder: '打开文件夹', status: { queued: '排队中', downloading: '下载中', processing: '处理中', done: '完成', error: '错误', cancelled: '已取消' } },
  batch: { title: '批量下载', subtitle: '下载多个 URL 或整个频道', tabUrls: 'URL 列表', tabChannel: '频道 / 播放列表', urlsLabel: 'URL（每行一个）', urlsPlaceholder: 'https://youtube.com/watch?v=...', urlsHint: '每行粘贴一个 URL', channelUrl: '频道 / 播放列表 URL', channelPlaceholder: 'https://www.youtube.com/@频道', limitVideos: '限制视频数量', limitHint: '最多视频数（0 = 全部）', dateAfter: '仅下载日期之后', dateBefore: '仅下载日期之前', reverseOrder: '倒序（从最旧开始）', reverseOrderHint: '从频道中最旧的视频开始', skipExisting: '跳过已下载', skipExistingHint: '使用 --download-archive', archiveFile: '存档文件路径', archiveHint: '跟踪已完成下载的文件', startBatch: '添加 {{n}} 个到队列', startChannel: '下载频道', urlCount: '{{n}} 个 URL', noUrls: '尚未输入 URL' },
  settings: { title: '设置', subtitle: '应用程序和二进制文件管理', binary: 'yt-dlp 二进制文件', status: '状态', installed: '已安装', missing: '缺失', localVersion: '本地版本', latestVersion: '最新版本', redownload: '重新下载', updateTo: '更新至 {{v}}', downloadLatest: '下载 {{v}}', language: '语言', languageHint: '选择您的显示语言', about: '关于', appName: '应用程序', version: '版本', framework: '框架', poweredBy: '驱动', platform: '平台' },
};
